# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-10 19:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='userprofile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.CharField(blank=True, help_text='Phone number', max_length=20, null=True)),
                ('invalid_attemps_count', models.IntegerField(blank=True, default=0, help_text='Number of invalid login attempts')),
                ('lock_out_end', models.DateTimeField(blank=True, help_text='Date time when account will be unlocked for logging in', null=True)),
            ],
            options={
                'db_table': 'userprofile',
            },
        ),
    ]
