# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-13 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('is_demo', models.BooleanField(default=False)),
                ('is_validated', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'organization',
            },
        ),
    ]
