# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-19 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limur', '0003_userprofile_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_moderator',
            field=models.BooleanField(default=False, help_text='Moderator role enabled'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='org_access_level',
            field=models.CharField(blank=True, choices=[('owner', 'Owner'), ('admin', 'Administrator'), (None, 'None')], default=None, max_length=8, null=True),
        ),
    ]
